# requiring the environment of NodeJS 10
image: node:12

pages:
  cache:
    paths:
    - ./node_modules/
 
  stage: deploy
  tags:
    - internal
  script:
    - npm install
    - npm run build
    - mv build/* public/
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - master # or dev, the branch you want to publish
