name: deploy

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Deploy product to OBS and refresh CDN
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Environment 
      uses: actions/setup-node@v1
      with:
        node-version: 12 

    - name: Build
      run: |
        npm install
        CI=false npm run build

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: main-artifact
        path: |
          build

    - name: Deploy
      uses: summer-ospp/infra-ci-s3-sync@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.HOMEPAGE_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.HOMEPAGE_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HOMEPAGE_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.HOMEPAGE_ENDPOINT }}
        SOURCE_DIR: 'build'

    - name: Refresh
      uses: summer-ospp/infra-ci-cdn-refresh@main
      env:
        CDN_AK: ${{ secrets.HOMEPAGE_CDN_AK }}
        CDN_SK: ${{ secrets.HOMEPAGE_CDN_SK }}
        CDN_REFRESH_URLS: ${{ secrets.HOMEPAGE_CDN_REFRESH_URLS }}
        CDN_REFRESH_TYPE: ${{ secrets.HOMEPAGE_CDN_REFRESH_TYPE }}

    - name: Sleep
      run: |
        sleep 300
    - name: Preheat
      uses: summer-ospp/infra-ci-cdn-preheat@main
      env:
        CDN_AK: ${{ secrets.HOMEPAGE_CDN_AK }}
        CDN_SK: ${{ secrets.HOMEPAGE_CDN_SK }}
        CDN_URLS: ${{ secrets.HOMEPAGE_CDN_URLS }}
        OBS_AK: ${{ secrets.HOMEPAGE_ACCESS_KEY_ID }}
        OBS_SK: ${{ secrets.HOMEPAGE_SECRET_ACCESS_KEY }}
        OBS_SERVER: ${{ secrets.HOMEPAGE_ENDPOINT }}
        OBS_BUCKET: ${{ secrets.HOMEPAGE_BUCKET }}
